spring:
  profiles:
    active: @deployType@
    #active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 0 mysql 1 oracle
dataType: 0
server:
  port: 8082
  servlet:
    context-path: /order-management-provider
  max-http-header-size: 4048576


