spring:
  application:
    name: order-api
  profiles:
    active: @deployType@
    #active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 50MB
      max-request-size: 50MB
  freemarker:
    check-template-location: false
server:
  port: 8081
  servlet:
    context-path: /order-api
  max-http-header-size: 4048576
  address: 10.1.28.133
